services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Z2obC9kg1512
      MYSQL_DATABASE: Conciertos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql_data: